name: charts_common
version: 0.8.1
description: A common library for charting packages.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  collection: ^1.14.5
  intl: 0.15.8
  logging: any
  meta: ^1.1.1
  vector_math: ^2.0.8
